### ISSUE TITLE
disable paste image

### ISSUE THREAD

**Issue by abr4xas** [chmln/vue-wysiwyg#111]
Hi i need to know how to disable paste image into the editor.

**Comment by steer629** [comment]
how do you enable it? I try to find the way enable

**Comment by abr4xas** [comment]
@steer629 I think that option is enabled by default.

**Comment by ZachitZo** [comment]
Hello, I have same problem. Images paste from 'ctrl+v' to editor. How can I disable it?

**Comment by jonaswebdev** [comment]
did you try it? maybe could solve :) 
```
 // set to 'true' this will insert plain text without styling when you paste something into the editor.
  forcePlainTextOnPaste: true,
```
