### ISSUE TITLE
Configuration not working to hide modules!

### ISSUE THREAD

**Issue by jazibsawar** [chmln/vue-wysiwyg#17]
I used the sample code to initiate this component but hideModule is not working in configuration for v1.2.6. 

`Vue.use(wysiwyg,{
  hideModules: { "bold": true, "table": true, "image": true }
})`

**Comment by lagmanzaza** [comment]
{
  hideModules: { "bold": true },
  image: {
    uploadURL: "/api/myEndpoint",
    dropzoneOptions: {}
  }
}

**Comment by jazibsawar** [comment]
Not working. Not hiding the modules. I think it is a bug.

**Comment by lagmanzaza** [comment]
I think  its support only "bold"

**Comment by jazibsawar** [comment]
But for me Bold is not working too. I am looking at the code. May be dev can help in this

**Comment by lagmanzaza** [comment]
Ok, I will try to fix it.

**Comment by lagmanzaza** [comment]
this repo is not mine but I will create PR for fix it

**Comment by lagmanzaza** [comment]
hideModules: { bold: true ,italic:true}

I think to update your modules and remove double quote

**Comment by lagmanzaza** [comment]
my configuration its work.

**Comment by jazibsawar** [comment]
I will try this. Thanks a lot @lagmanzaza

**Comment by jazibsawar** [comment]
Without quotes also not working. Can you tell me how you are loading this compotent? I am loading this in main.js
`import wysiwyg from "vue-wysiwyg";
Vue.use(wysiwyg,{
  hideModules: { bold: true, table: true, image: true }
})`

Then I my components I do `<wysiwyg v-model="recipeModel.content" />`

**Comment by lagmanzaza** [comment]
Did you forget to add @import "~vue-wysiwyg/dist/vueWysiwyg.css";  to your CSS file

**Comment by jazibsawar** [comment]
No i didn't. It is looking great otherwise

**Comment by mgyugcha** [comment]
Hi, I have the same problem :S

**Comment by jazibsawar** [comment]
I have achieved that by using simple css. @mgyugcha

**Comment by chmln** [comment]
Hello,

Please see if `v.1.2.7` fixes the problem.
Thank you.

**Comment by jazibsawar** [comment]
Yes, @chmln it fixed it. Awesome.

**Comment by rugor** [comment]
This issue persists for me in v. 1.2.7

Config: 

```
import wysiwyg from "vue-wysiwyg"
Vue.use(wysiwyg, {
  hideModules: { 
    "headings": true,
    "hyperlink": true,
    "image": true,
    "table": true,
    "separator": true
  }
})
```

Yields: 
![screenshot 2017-10-10 10 59 04](https://user-images.githubusercontent.com/359147/31402186-1a52da86-adaa-11e7-9403-2f8f168bcd85.png)

Resolving with css for now

**Comment by jazibsawar** [comment]
try to use 
`Vue.use(wysiwyg, {
  hideModules: { 
    headings: true,
    hyperlink: true,
    image: true,
    table: true,
    separator: true
  }
})`

**Comment by jonaswebdev** [comment]
Hi, I have the same issue here, I'm trying to hide the "Image" button but doesn't work :(

```
const wysiwygOptions = {
  hideModules: {
    image: true
  },
};
Vue.use(wysiwyg, wysiwygOptions);
```

Some idea excepting hiding via CSS?
