### ISSUE TITLE
Firebase endpoints for uploadURL

### ISSUE THREAD

**Issue by adarshsosale** [chmln/vue-wysiwyg#22]
I'm having issues setting this up with firebase. Is the endpoint for the firebase storage the same as the databaseURL? Help with regard to this is greatly appreciated! (And an example perhaps)

**Comment by chmln** [comment]
Hello,

This component simply sends the image to the specified endpoint.
How you handle it server-side is up to you. 

If I was familiar with firebase I'd help, but unfortunately I'm not.

**Comment by adarshsosale** [comment]
No problem. Thanks a lot! Great plugin!
