### ISSUE TITLE
Using the component multiple times in the same parent

### ISSUE THREAD

**Issue by ecerroni** [chmln/vue-wysiwyg#23]
First of all, kudos for you work as this is a very simple yet fully working component. It's slim and I like it much more that those bloated ones :+1: 

It is generally working well but when I use it in a v-for directive. 

**Context**:
I have multiple articles in my form and each of them have a wysiwyg component. They are added and removed dynamically. So each form component can have 0+ wysiwyg content at any time.
```
<el-form-item
         v-for="(article, index) in campaign.articles"
         :key="index"
         :prop="'articles.' + index + '.value'"
         :id="`form_campaign_article_${index + 1}`"
       >
```

`<wysiwyg :ref="`wysiwyg_article_${index + 1}`" v-model="article.content" />`

...

**Issue**:
When I add a link to one of the wysiwyg all others get that link too.

![link_not-working-as-expected](https://user-images.githubusercontent.com/11174327/32010973-a41e8688-b9b3-11e7-96b8-20f94c60bae5.png)

**Expected behavior**:
The link should be added only to the current wysiwyg I'm writing on

I'd like to help if you can give me some directions on what I should look for to fix the issue

**Comment by nawalnew** [comment]
Same Issue here. Would be great if there is any solution for multiple Instances at one page

**Comment by Samy-Amar** [comment]
For those looking PR is in #24
