### ISSUE TITLE
issue headline/image/link etc.

### ISSUE THREAD

**Issue by nawalnew** [chmln/vue-wysiwyg#25]
Hello,
I have an issue when selecting something else than headline. 
When I click on Link than the same dropdown appears a s Headline "h1, h2, h3". 

I don't know where the bug is. 
Even when I try to hide the "headings" module, it appears. 

Some advice? 

My main.js
`
import wysiwyg from "vue-wysiwyg";
import "vue-wysiwyg/dist/vueWysiwyg.css";
Vue.use(wysiwyg, {
  hideModules: {
    headings: true
  }
}); // config is optional. more below`

**Comment by invmatt** [comment]
Having the same issue. In addition to this when selecting a heading the following error appears:

`vueWysiwyg.js?5768:1 Uncaught TypeError: Cannot read property 'focus' of undefined
    at VueComponent.exec (vueWysiwyg.js?5768:1)
    at r.boundFn (vue.runtime.esm.js?ff9b:185)
    at r.l.emitEvent (vueWysiwyg.js?5768:1)
    at r.l.emit (vueWysiwyg.js?5768:1)
    at VueComponent.insertHeading (vueWysiwyg.js?5768:1)
    at boundFn (vue.runtime.esm.js?ff9b:186)
    at invoker (vue.runtime.esm.js?ff9b:1933)
    at HTMLButtonElement.fn._withTask.fn._withTask (vue.runtime.esm.js?ff9b:1768)`

**Comment by rodrigoAbril** [comment]
Here is a demo of the bug 
https://codesandbox.io/s/jn0ovr2p9y

**Comment by rodrigoAbril** [comment]
@invmatt @nawalnew 
if you upgrade vue to today's vue@2.5.3 release the problem is fixed

**Comment by invmatt** [comment]
@rodrigoAbril Confirmed. Updating has solved the problem. Thanks for the quick reply.

**Comment by rodrigoAbril** [comment]
well the issue is gone but now when you want to add a table you get this error:

ReferenceError
table is not defined
VueComponent.insertTable...

**Comment by chmln** [comment]
Looks like changes in Vue are causing some errors.
Perhaps I could try rebuilding the library against the latest version.

**Comment by nawalnew** [comment]
Same here, most issues fixed with update. 
But cant create table -.-

**Comment by chmln** [comment]
The version on master is now running against latest Vue without problems.
There will also be UX improvements and hopefully a fix for the link module.

Thanks all for your patience 👍

**Comment by chmln** [comment]
Hi all,

I've published a new version under vue-wysiwyg@next at npm.
This version includes a fix for the hyperlink module, rewritten table module, usability improvements, and is built against the latest version of vue (2.5.8).

Please try it out and let me know if all the problems are fixed.

Thank you

**Comment by nawalnew** [comment]
Thank you @chmln , 
It works better with all functionality. 

I have just one Issue with multiple Instances of the editor and the tables. 

Do you have an Idea how to solve this that I can use multiple Instances of the editor on one page? :) 
<img width="698" alt="bildschirmfoto 2017-11-24 um 10 10 51" src="https://user-images.githubusercontent.com/12047483/33203304-df11d6c4-d0ff-11e7-8fa0-7a402d8895ee.png">

**Comment by chmln** [comment]
@nawalnew Yes, multiple instances will be available by next release :)
