### ISSUE TITLE
Link module does not work properly

### ISSUE THREAD

**Issue by KsCorrales** [chmln/vue-wysiwyg#27]
i try to use the link module but i can't click in the inputs of the link module only works if use the tab button and also is printed the url content next to the insert button.

### Image:
![Image](https://i.imgur.com/qvOgpI9.jpg)

**Comment by chmln** [comment]
Hey @KsCorrales 

Installing `vue-wysiwyg@next` from npm should fixe the issue.

**Comment by KsCorrales** [comment]
yes, now works but works wrong, add twice the link when i click insert or press enter button, after that all is broke and show this errors :man_facepalming: 

![Image](https://i.imgur.com/vWdqUgA.jpg)

**Comment by KsCorrales** [comment]
I think it's because 2 listeners are created when add twice

**Comment by chmln** [comment]
Should be fixed in the latest version.
Please re-open if any issues occur otherwise.
