### ISSUE TITLE
Config options not working?

### ISSUE THREAD

**Issue by defaye** [chmln/vue-wysiwyg#3]
So in my project I've done the following:

```
import wysiwyg from "vue-wysiwyg";
Vue.use(wysiwyg, {
    hideModules: [
        "bold",
        "image",
    ],
});
```

Buuut.... I still get the image and bold options.

![image](https://cloud.githubusercontent.com/assets/1431026/25333397/edc02b2e-28e1-11e7-96d8-adf412c50f71.png)

Any ideas? It would be nice if you updated the docs with the available options too, because it isn't necessarily obvious what they would be.

**Comment by chmln** [comment]
See https://github.com/chmln/vue-wysiwyg#config-options
