### ISSUE TITLE
Issue with bolding / highlighting

### ISSUE THREAD

**Issue by alexhiggins** [chmln/vue-wysiwyg#31]
Hey,

I'm getting issues when trying to bold / highlight text - using Chrome 61 / Firefox 57.

Using the example site i can replicate it - https://chmln.github.io/vue-wysiwyg/

Video - https://monosnap.com/file/RxgVx6PH0qwwIeECi2kWgsacanEMBs

Thanks!

**Comment by chmln** [comment]
Hey Alex,

Thanks for reporting this.
This must be the same core issue as #32

Will fix this asap.
