### ISSUE TITLE
multiple lists behave buggy

### ISSUE THREAD

**Issue by codeofsumit** [chmln/vue-wysiwyg#32]
Hey there,

just searched for a wysiwyg editor and tested this out on the demo page. The lists did not work as expected and just wanted to let you know. Here's a GIF:
![vuewysiwyg](https://user-images.githubusercontent.com/2399810/33584317-97840c2a-d913-11e7-8f3c-d1cdeac66aa2.gif)

**Comment by chmln** [comment]
Hey @codeofsumit 

Thanks a lot for reporting this!
I'm guessing this has to do with the editor not being focused properly after clicking the list buttons.

I'll fix this in a new release (soon).
