### ISSUE TITLE
DropZone not working and not giving any errors

### ISSUE THREAD

**Issue by Peter2962** [chmln/vue-wysiwyg#35]
Hi,

Hope you are well? Could you please help with the dropzone? When i click on the picture icon, it does not show the dropzone. Please see image for more imformation. Thank you.

![capture-132](https://user-images.githubusercontent.com/18626464/34601101-2be72f7a-f203-11e7-9ba9-bf5af30c7ce4.png)

**Comment by invmatt** [comment]
Having the same issue. When running in development mode the dropzone area appears correctly. Once compiled for production the dropzone just shows an empty div.

Package version is 1.3.2
No errors are logged to console.

![image](https://user-images.githubusercontent.com/1536844/34604062-69551318-f1fe-11e7-9cc8-78d74e9cb9dd.png)

**Comment by chmln** [comment]
This random error was on Vue's part or maybe uglifyjs.
Apparently components being named in lowercase causes these errors, while nothing is logged in the console.

v1.3.4 is out with the fix.

**Comment by invmatt** [comment]
@chmln Updated to 1.3.5 and it now logs out the following error:

`Uncaught ReferenceError: Dropzone is not defined`
