### ISSUE TITLE
Enclosing content in a defined tag

### ISSUE THREAD

**Issue by lcini17** [chmln/vue-wysiwyg#37]
Currently it seems that any content included in the editor is enclosed within a default div tag. Are there any plans to improve this and include a specific tag, for example, [p] ..[/p]?

Thanks in advance.

**Comment by isaacsant** [comment]
Following ticket as I'm experiencing a similar issue. Thanks

**Comment by chmln** [comment]
Hello,

Yes, this should be possible. Instead of divs, paragraphs can be separated by `p` tags instead.
https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Editable_content#Differences_in_markup_generation

Is this what you meant?
