### ISSUE TITLE
Insert table not working

### ISSUE THREAD

**Issue by maxrgus** [chmln/vue-wysiwyg#39]
Version 1.4.0

Error: Uncaught TypeError: Failed to execute 'addRange' on 'Selection': parameter 1 is not of type 'Range'.

How to reproduce: Present on demo page https://chmln.github.io/vue-wysiwyg/

**Comment by sempixel** [comment]
It seems **Header** doesn't work either.

**Comment by NicolasPK** [comment]
@sempixel **Headings**, **link**, **table** and **image upload** don't work for me on Chrome 63.0 either. I've got the same error as @maxrgus.

**Comment by sempixel** [comment]
@NicolasPK Yeah sorry, I was on 1.3.3 for testing purposes.
With 1.4.0, I've got same errors.

**Comment by chmln** [comment]
Thanks for raising the issue @maxrgus

I will publish a fix asap
