### ISSUE TITLE
Is there a way to remove spacers with modules?

### ISSUE THREAD

**Issue by chris-faulkner** [chmln/vue-wysiwyg#50]
Hi, thanks for your work I like the simplicity.

I was just wondering if it's possible to remove spacers when removing modules as I've ended up with double spacer in the toolbar:
![screenshot 2018-02-26 14 47 52](https://user-images.githubusercontent.com/25483015/36676738-63ea1a20-1b04-11e8-80ca-445f96785b6a.png)

It's not a big issue just would be nice to clean up.

**Comment by chmln** [comment]
@chris-faulkner of course. you can use CSS for that. Just hide the :nth-child(4)

**Comment by chris-faulkner** [comment]
I feel dumb for not realising that, thanks man!
