### ISSUE TITLE
Add strikethrough <s>

### ISSUE THREAD

**Issue by amdelamar** [chmln/vue-wysiwyg#52]
Any plans to add a `<s>` strikethrough button?

> **Example:** I am <s>not sure</s> certain this feature is used often.

**Comment by chmln** [comment]
@amdelamar you can easily create your own custom module for this.
See https://github.com/chmln/vue-wysiwyg/blob/master/src/editor/examples/customModule_simple.js for example

**Comment by amdelamar** [comment]
Ok, so its extensible... but do you have plans to add more buttons/features to this wysiwyg?
Because I have other buttons like `img src="//"` urls and separating `<code>` and `<pre><code>` for code snippets and blocks.

What are your plans for vue-wysiwyg?
