### ISSUE TITLE
dropzoneOptions not working

### ISSUE THREAD

**Issue by antonioandrade** [chmln/vue-wysiwyg#57]
Dropzone options do not seem to be properly passed in as per the documentation.
In practice, configuring custom upload headers as below won't work:

```javascript
Vue.use(wysiwyg, {
    image: {
        uploadURL: "/api/myEndpoint",
        dropzoneOptions: {
              "my-header": "some data"
        }
      },
});
```

**Comment by chmln** [comment]
@antonioandrade https://rowanwins.github.io/vue-dropzone/docs/dist/index.html#/installation

Aren't headers supposed to be passed in a `headers` object?

Like

```js
dropzoneOptions: {
      headers: { "Header Key": "header value" }
}
```

**Comment by feroj21** [comment]
@chmln I am adding header object as like as described in https://rowanwins.github.io/vue-dropzone/docs/dist/index.html#/installation. But it still not working!
