### ISSUE TITLE
Additional param in dropzone?

### ISSUE THREAD

**Issue by eard7** [chmln/vue-wysiwyg#6]
Hi, first of all thanks for share this component.
I have one doubt, how can i pass additional params to the dropzone component? i need to send a token in the upload request to grant permission and i can't find how to do that with your component.
Thanks in advance!

**Comment by chmln** [comment]
Hello,

I'll make it possible to pass options to `dropzone` by next release.
Thanks for the idea!

**Comment by ecerroni** [comment]
@chmln I have the same problem. I need to pass a token to the api endpoint for authorization.

So it would be great if we can pass some custom headers.

Do you know more or less when the next release will happen?

Thanks :)

**Comment by distortia** [comment]
Any update on this? Really looking to use this project but I need to pass in a token to my endpoint.

**Comment by chmln** [comment]
Should be possible as of `v1.2.4`, out now.
See https://github.com/chmln/vue-wysiwyg/blob/master/README.md#config-options
