### ISSUE TITLE
Code licensing

### ISSUE THREAD

**Issue by batmah** [chmln/vue-wysiwyg#62]
Hello,
I did not found any information how is this project licensed.
Can author add information about this, 
so we can decide can we use this component in commercial projects?
Thanks.

**Comment by chmln** [comment]
@batmah the project is MIT licensed. you can use it freely in commercial projects.
See https://github.com/chmln/vue-wysiwyg/blob/master/package.json#L13

I will add a LICENSE file to prevent further confusion.
