### ISSUE TITLE
does it support auto save?

### ISSUE THREAD

**Issue by fengchangfight** [chmln/vue-wysiwyg#74]

**Comment by mchampaneri** [comment]
You can do it using watch on content using vuejs watch property.
It will work like autosave on change
For example 

```
watch:{
 content: function(){
   // api calls to save the current data //
  } 
}
```

**Comment by WebLab-ImpCode** [comment]
`<wysiwyg v-model="myHTML" v-on:change="onChange"/>`
`methods: {
            onChange: function(content) {
                     //your logic
            }
}`

**Comment by fengchangfight** [comment]
I've figured out a way to do the auto save, basically just use the content change event， but find a way for debounce(could be in many ways).  thank you all for answering, I'll just close the  issue now..
