### ISSUE TITLE
Replace <div> wrapping with <p>

### ISSUE THREAD

**Issue by Konzeptcode** [chmln/vue-wysiwyg#75]
Hi,
is it possible to disable the <div> wrapping of the plugin for new lines and replace them with <p>?

Current:
`<div>dfgsdgfsg</div><div>bvxdgbydipoj<b>dübj</b>d</div><div>cvnbcncvncvncv</div>`

Aiming:
`<p>dfgsdgfsg</p><p>bvxdgbydipoj<b>dübj</b>d</p><p>cvnbcncvncvncv</p>`

**Comment by itsyub** [comment]
you can do it by specifying `paragraphSeparator` config.

Sample code
```
import wysiwyg from "vue-wysiwyg";
Vue.use(wysiwyg, {paragraphSeparator: 'p'}); 
```

**Comment by ZachitZo** [comment]
It works, but first stroke of handle input text have not wrap. Only next paragraphs start to wrap, first - not!
