### ISSUE TITLE
content of vue-wysiwyg is not reactive.

### ISSUE THREAD

**Issue by KsCorrales** [chmln/vue-wysiwyg#9]
if i change the data model out of the wysiwyg, the editor not update the changes how can i make it reactive?.

or how can i clear the content?

**Comment by DamienDabernat** [comment]
Use :

```
this.$children[2].innerHTML = this.HTML + someText;
this.$children[2].exec()
```

Where this.HTML is your parent's data

**Comment by KsCorrales** [comment]
@DamienDabernat wooow thanks  :+1:

**Comment by josh1881** [comment]
Any chance you can elaborate on your answer somewhat?  I'm a bit of a newb and I'm really struggling.  I have a dropdown where a user selects a "content block" from the database and that data should get loaded into the HTML editor for editing.  When I load the first one, it works fine, but subsequent selections do not update at all.

**Comment by KsCorrales** [comment]
@josh1881 when you use `this.$children` you access to all children components in your vue instance, the `[0]` is the first component, you should make sure if the children selected is the editor, And already just assign the text example:

`this.$children[2].innerHTML = 'Assign text inside the editor'` if the Wysiwyg  component is the children[2]

**Comment by josh1881** [comment]
Ah, yes... thanks for clearing that up.  I was using a `ref` to target the component, and thought I was somehow accessing the children of the component.  Changed my code to `this.$refs.contentEditor.innerHTML = '...'` and it works like a charm now.  Thanks for the clarification.

**Comment by chmln** [comment]
Hello,

Updating content using `$refs` or `$children` is no longer necessary as of `v1.2.3` and 30761e7be9e78fb22ae858928beb4ff15dfe166f.
